{% set name = "neurotic" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 846b02aac14e6528262f92425df1228c582c037e3274fff01de96b4daf8cef97

build:
  number: 1
  entry_points:
    - neurotic=neurotic.scripts:main
  skip: True  # [py<36]

requirements:
  host:
    - pip
    - python
  run:
    - av
    - ephyviewer >=1.3.0
    - numpy
    - packaging
    - pandas
    - pydrive2
    - pyqt          # [not win]
    - pyqt !=5.9.2  # [win]
    - python
    - python-neo >=0.7.2
    - pyyaml
    - quantities
    - requests
    - scipy
    - setuptools
    - toml
    - tqdm

test:
  imports:
    - neurotic
    - neurotic.datasets
    - neurotic.gui
    - neurotic.gui.icons
    - neurotic.tests
  commands:
    - neurotic --help

about:
  home: https://github.com/jpgill86/neurotic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Curate, visualize, annotate, and share your behavioral ephys data using Python
  description: |
    neurotic is an app for Windows, macOS, and Linux that allows you to easily
    review and annotate your electrophysiology data and simultaneously captured
    video. It is an easy way to load your Neo-compatible data into ephyviewer
    without doing any programming. Share a single metadata file with your
    colleagues and they too will quickly be looking at the same datasets!
  doc_url: https://neurotic.readthedocs.io/
  dev_url: https://github.com/jpgill86/neurotic

extra:
  recipe-maintainers:
    - jpgill86
